services:
  backend:
    build: ./Av1-Backend
    container_name: arteideas-backend
    ports:
      - "9000:8000"
    restart: always
    env_file: .env
    depends_on:
      - db
    environment:
      - DB_ENGINE=django.db.backends.mysql
      - DB_HOST=db
      - DB_PORT=3306
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - FRONTEND_URL=${FRONTEND_URL}

  frontend:
    build: ./Av1-Frontend
    container_name: arteideas-frontend
    ports:
      - "3000:80"
    restart: always
    env_file: ./Av1-Frontend/.env

  db:
    image: mysql:8.0
    container_name: arteideas-db
    restart: always
    env_file: .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

